### ISSUE TITLE
SMTP Failing

### ISSUE THREAD

**Issue by itkville** [andrewscaya/mod_simpleemailform#28] opened 2018-02-09 23:32 UTC
I have Joomla installed on a Windows server and I've setup my SMTP settings in Joomla Global Config using port 25 with authentication to my exchange 2010 mail server.  Send test email works just fine from Joomla itself, but when trying to submit email from the contact form it fails with SMTP Connect() failed.  What is your module doing for SMTP so that it isn't using the same settings as Joomla itself?  Any ideas how I can fix this so that it uses the settings in Joomla or something?  I don't see anywhere to edit the SMTP settings within the module?  Thanks in advance!

**Comment by andrewscaya** [comment] 2018-02-10 03:46
Hello @itkville --

Indeed, there are no SMTP settings in the module's configuration panel as we proxy all email related actions to JMail (Joomla Mailer). Thus, what works for Joomla, should work for Simple Email Form too.

Therefore, I am puzzled as to how you can send emails through Exchange from Joomla directly, but not from our module. Have you checked your logs? Have you tried debugging? Maybe your mail server is refusing to send the email because of the "FROM" field value (it's considering the email to be SPAM mail based on the client's declared domain in order to avoid being an open relay). If this is the case, you would have to create an ACL within Exchange that would be based upon the IP address of the client SMTP connection in order to allow the mail to be relayed by your Exchange server?

Just to make absolutely sure that the problem is not coming from our module, I will have a look into this and test the latest versions of Joomla and SEF on a Windows 2016 Server with a Microsoft Exchange Server running on it.

Will get back to you ASAP.

Best regards,

Andrew

**Comment by andrewscaya** [comment] 2018-02-10 03:52
@itkville --

And, if any of the above mentioned suggestions work, please let us know.

**Comment by andrewscaya** [comment] 2018-02-13 20:23
Hi @itkville,

I have tested SEF with Exchange 2016 running on a Windows Datacenter 2016 server and everything is working as expected.

I submit the form using SEF v.2.1.0:
![sef_form_submitted](https://user-images.githubusercontent.com/15166159/36171728-c61e53ec-10d1-11e8-9fd5-aa8866cd4976.png)

And, I receive the email in my Exchange mailbox:
![exchange_email_reception](https://user-images.githubusercontent.com/15166159/36171752-d3b7ebe4-10d1-11e8-9b28-22ff00ff6c3b.png)

It is most likely that you are having a relay issue that you can fix by configuring a "receive connector" in the "mail flow" section of Exchange's Admin panel.

Best of luck and thanks for your interest in the Simple Email Form module!

Best regards,

Andrew

**Comment by andrewscaya** [comment] 2018-02-13 20:34
@itkville --

I am closing this issue, but I will leave the conversation open in case you have further comments/questions.

Best regards,

Andrew

**Closed by andrewscaya** 2018-02-13 20:34 UTC
Labels: help wanted
